services:
  portainer:
    image: portainer/portainer-ee:${PORTAINER_VERSION:-latest}
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      PORTAINER_ADMIN_USER: ${PORTAINER_USER:-admin}
      PORTAINER_ADMIN_PASSWORD: ${PORTAINER_PASSWORD:-password}
      TZ: ${TZ:-Europe/Lisbon}
#      UID: ${PORTAINER_PUID:-1000}
#      GID: ${PORTAINER_PGID:-1000}
#    user: "${PORTAINER_PUID:-1000}:${PORTAINER_PGID:-1000}"
    security_opt:
      - no-new-privileges:true
    networks:
      - portainer_net

networks:
  portainer_net:
    name: portainer_net
    driver: bridge

volumes:
  portainer_data:
    name: "portainer_data"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PATH_PREFIX-/srv/}${BASE_PATH}${NAMESPACE:-portainer}${PGS_NAMESPACE:-/data}
