services:
  n8n:
    image: n8nio/n8n:latest
    hostname: n8n
    container_name: n8n
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      # Basic Configuration
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-UTC}
      - N8N_USER_FOLDER=${N8N_USER_FOLDER:-/home/node/.n8n}
      
      # Security
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-password}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-your-secret-key}
      
      # Database Configuration (PostgreSQL recommended for production)
      - DB_TYPE=${DB_TYPE:-postgres}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE:-n8n}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST:-postgres}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT:-5432}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER:-n8n}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD:-n8n}
      
      # Email (optional)
      - N8N_EMAIL_MODE=${N8N_EMAIL_MODE:-}
      - N8N_SMTP_HOST=${N8N_SMTP_HOST:-}
      - N8N_SMTP_PORT=${N8N_SMTP_PORT:-587}
      - N8N_SMTP_USER=${N8N_SMTP_USER:-}
      - N8N_SMTP_PASS=${N8N_SMTP_PASS:-}
      - N8N_SMTP_SENDER=${N8N_SMTP_SENDER:-}
      
      # Execution Settings
      - EXECUTIONS_DATA_SAVE_ON_ERROR=${EXECUTIONS_DATA_SAVE_ON_ERROR:-all}
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=${EXECUTIONS_DATA_SAVE_ON_SUCCESS:-all}
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=${EXECUTIONS_DATA_SAVE_ON_PROGRESS:-false}
      - EXECUTIONS_DATA_PRUNE=${EXECUTIONS_DATA_PRUNE:-true}
      - EXECUTIONS_DATA_MAX_AGE=${EXECUTIONS_DATA_MAX_AGE:-336}
      
      # Performance and Scaling
      - EXECUTIONS_MODE=${EXECUTIONS_MODE:-regular}
      - QUEUE_BULL_REDIS_HOST=${QUEUE_BULL_REDIS_HOST:-redis}
      - QUEUE_BULL_REDIS_PORT=${QUEUE_BULL_REDIS_PORT:-6379}
      
    volumes:
      - data:${N8N_USER_FOLDER:-/home/node/.n8n}
    networks:
      - n8n_network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:${PGS_VERSION:-16-alpine}
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    networks:
      - postgres-net
    ports:
      - "${PGS_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${DB_POSTGRESDB_DATABASE:-n8n}
      POSTGRES_USER: ${DB_POSTGRESDB_USER:-n8n}
      POSTGRES_PASSWORD: ${DB_POSTGRESDB_PASSWORD:-n8n}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: ${TZ:-Europe/Lisbon}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  #    user: "${PGS_PUID:-1000}:${PGS_PGID:-1000}"
#    platform: "linux/amd64,linux/arm64"

  redis:
    image: redis:7-alpine
    hostname: redis
    volumes:
      - redis:/data
    networks:
      - n8n_network
#    platform: "linux/amd64,linux/arm64"


volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PATH_PREFIX-/srv/}${BASE_PATH}${NAMESPACE:-n8n}${N8N_NAMESPACE:-/data}
  postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PATH_PREFIX-/srv/}${BASE_PATH}${NAMESPACE-n8n}${PGS_NAMESPACE-/postgres}
  redis:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PATH_PREFIX-/srv/}${BASE_PATH}${NAMESPACE:-n8n}${REDIS_NAMESPACE:-/redis}

networks:
  n8n_network:
    driver: bridge