services:
  mariadb:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    networks:
      - sql-net
    ports:
      - "${MARIADB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MARIADB_DATABASE:-db}
      MYSQL_USER: ${MARIADB_USER:-user}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD:-password}
      TZ: ${TZ:-Europe/Lisbon}
    volumes:
      - sql_data:/var/lib/mysql
#    user: "${MARIADB_PUID:-1000}:${MARIADB_PGID:-1000}"

  postgres:
    image: postgres:${PGS_VERSION:-16-alpine}
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    networks:
      - postgres-net
    ports:
      - "${PGS_PORT:-5432}:5432"
    environment:
      PGS_USER: ${PGS_ROOT_USER:-postgres}
      PGS_PASSWORD: ${PGS_ROOT_PASSWORD:-changeMe}
      PGS_DB: ${PGS_DB:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: ${TZ:-Europe/Lisbon}
    volumes:
      - PGS_data:/var/lib/postgresql/data
#    user: "${PGS_PUID:-1000}:${PGS_PGID:-1000}"

  adminer:
    image: adminer:latest
    container_name: adminer
    hostname: adminer
    restart: unless-stopped
    depends_on:
      - mariadb
      - postgres
    networks:
      - sql-net
      - postgres-net
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
      UPLOAD_MAX_FILESIZE: 256M
      POST_MAX_SIZE: 256M
      TZ: ${TZ:-Europe/Lisbon}
#    user: "${ADMINER_PUID:-1000}:${ADMINER_PGID:-1000}"


volumes:
  PGS_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PATH_PREFIX-/srv/}${BASE_PATH}${NAMESPACE-db}${PGS_NAMESPACE-/postgres}
  sql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PATH_PREFIX-/srv/}${BASE_PATH}${NAMESPACE-db}${MARIADB_NAMESPACE-/mariadb}

networks:
  sql-net:
  postgres-net: