metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - memory
      - network
      - process
      - process_summary
      - uptime
    period: 10s
    processes: ['.*']
    process.include_top_n:
      by_cpu: 5
      by_memory: 5
    hostfs: "/hostfs"

  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s

setup.dashboards:
  enabled: true
  host: "https://kibana:5601"
  ssl.enabled: true
  ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca.crt"]
  username: "${ELK_ES_USER}"
  password: "${ELK_ES_PASSWORD}"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  ssl.enabled: true
  ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca.crt"]
  ssl.certificate: "/usr/share/metricbeat/certs/metricbeat.crt"
  ssl.key: "/usr/share/metricbeat/certs/metricbeat.key"